# Generated by Django 4.2.6 on 2023-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNumber', models.IntegerField(blank=True, null=True)),
                ('CompanyEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('CompanyPassword', models.CharField(blank=True, max_length=100, null=True)),
                ('CompanyLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
