# Generated by Django 4.2.6 on 2023-10-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_companydb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydb',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
