# Generated by Django 4.2.6 on 2023-10-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_jobdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdb',
            name='CompanyEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
