# Generated by Django 4.2.6 on 2023-10-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_jobdb_companyemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydb',
            name='Address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='companydb',
            name='Website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
