# Generated by Django 4.2.6 on 2023-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_jobdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='CompImages'),
        ),
    ]
