# Generated by Django 4.2.6 on 2023-10-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_alter_jobdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdb',
            name='BriefDescription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobdb',
            name='PreferredSkills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
