# Generated by Django 4.2.6 on 2023-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_alter_jobdb_briefdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdb',
            name='BriefDescription',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='jobdb',
            name='PreferredSkills',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
