# Generated by Django 4.2.6 on 2023-11-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_alter_jobdb_briefdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydb',
            name='Description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
