# Generated by Django 4.2.6 on 2023-11-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_alter_companydb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdb',
            name='Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
