# Generated by Django 4.2.6 on 2023-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_jobdb_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdb',
            name='Experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdb',
            name='JobType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdb',
            name='Salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdb',
            name='Vacancy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
