# Generated by Django 4.2.6 on 2023-11-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_jobdb_experience_jobdb_jobtype_jobdb_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdb',
            name='Website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
