# Generated by Django 4.2.6 on 2023-11-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_companydb_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='CategoryImage')),
            ],
        ),
    ]
