# Generated by Django 4.2.6 on 2023-11-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_jobcategorydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdb',
            name='JobCategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
