# Generated by Django 4.2.6 on 2023-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0018_jobdb_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdb',
            name='BriefDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdb',
            name='PreferredSkills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
