# Generated by Django 4.2.6 on 2023-11-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_contactdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='Message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='Subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
