# Generated by Django 4.2.6 on 2023-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_contactdb_email_alter_contactdb_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployementDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('CurrentCompanyName', models.CharField(blank=True, max_length=50, null=True)),
                ('Designation', models.CharField(blank=True, max_length=50, null=True)),
                ('JoiningDate', models.DateField(blank=True, max_length=50, null=True)),
                ('CurrentSalary', models.CharField(blank=True, max_length=50, null=True)),
                ('Skills', models.CharField(blank=True, max_length=50, null=True)),
                ('NoticePeriod', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
