# Generated by Django 4.2.6 on 2023-11-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_employementdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledb',
            name='CurrentCompanyName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofiledb',
            name='CurrentSalary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofiledb',
            name='Designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofiledb',
            name='JoiningDate',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofiledb',
            name='NoticePeriod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofiledb',
            name='Skills',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
