# Generated by Django 4.2.6 on 2023-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_delete_employementdb_userprofiledb_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledb',
            name='PassoutYear',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
