# Generated by Django 4.2.6 on 2023-11-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_alter_userprofiledb_passoutyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='Resume')),
                ('JobTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
