# Generated by Django 4.2.6 on 2023-12-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_applicationdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledb',
            name='FullName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
