# Generated by Django 4.2.6 on 2023-12-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_userprofiledb_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdb',
            name='FullName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
