# Generated by Django 4.2.6 on 2023-12-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_applicationdb_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
