# Generated by Django 4.2.6 on 2023-12-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_alter_registerdb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='status',
        ),
    ]
